spring:
  application:
    name: TrafficStudyPart3

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 10s

    instances:
      customRateLimiter:
        limitForPeriod: 1
        limitRefreshPeriod: 5s
        timeoutDuration: 0

      all:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5 # 판단할 기준 (ex. 최근 몇개의 요청을 기준으로 판단할건지?)
        sliding-window-type: count_based # window-size 는 어떤 것을 기준으로 카운트할지
        minimum-number-of-calls: 3 # 서킷 작동 기준 호출 수
        permitted-number-of-calls-in-half-open-state: 2 # half-open 상태에서 허용할 호출 수
        wait-duration-in-open-state: 3s # 서킷이 열린 상태로 있는 시간
        failure-rate-threshold: 50 # 실패율 기준



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
