spring:
  application:
    name: TrafficStudyPart3

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 1 # ??? ??? ???
        limitRefreshPeriod: 5s # ???? ??? ? ??
        timeoutDuration: 10s # ??? ?? ?? ? ??

    instances:
      customRateLimiter:
        limitForPeriod: 1 # ??? ??? ???
        limitRefreshPeriod: 5s # ???? ??? ? ??
        timeoutDuration: 0 # ??? ?? ?? ? ??

      all:
        limitForPeriod: 2 # ??? ??? ???
        limitRefreshPeriod: 5s # ???? ??? ? ??
        timeoutDuration: 0 # ??? ?? ?? ? ??

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
