POST http://localhost:8080/api/v1/orders/place
Content-Type: application/json

{
  "userId": "user-001",
  "productId": "product-3",
  "quantity": 10,
  "totalAmount": 10000
}
###
POST http://localhost:8080/api/v1/orders/search
Content-Type: application/json

{
  "userId": "user-001",
"orderId": "639c4981b5b842c29726fd8d766e2d55"
}

