POST http://localhost:8080/api/v1/orders/place
Content-Type: application/json

{
  "userId": "user-001",
  "productId": "product-0",
  "quantity": 10,
  "totalAmount": 6000
}
###

POST http://localhost:8080/api/v1/orders/place
Content-Type: application/json

{
  "userId": "user-001",
  "productId": "product-0",
  "quantity": 10,
  "totalAmount": 6000
}
###
POST http://localhost:8080/api/v1/orders/search
Content-Type: application/json

{
  "userId": "user-001",
"orderId": "a4cb35d261ca4a93a49c5663e3da58a1"
}

