GET http://localhost:8080/api/v1/simulation?duration=10000&size=10
###
GET http://localhost:8080/api/v1/simulation?duration=10&size=5
###
GET localhost:8080/api/v1/ratelimiter/getRateLimiter
###
GET localhost:8080/api/v1/ratelimiter/getRateLimiter2
###
GET localhost:8080/api/v1/threads
###
GET localhost:8080/api/v1/circuit?code=123456